"""Crear tabla incidents y campo umbral_fallos_consecutivos

Revision ID: 1cef3a500f92
Revises: ece99b38aab1
Create Date: 2026-08-30 07:04:06.866530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cef3a500f92'
down_revision: Union[str, None] = 'ece99b38aab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monitor_id', sa.UUID(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('causa', sa.String(), nullable=False),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_monitor_id'), 'incidents', ['monitor_id'], unique=False)
    op.add_column('monitors', sa.Column('umbral_fallos_consecutivos', sa.Integer(), nullable=False, server_default='2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'umbral_fallos_consecutivos')
    op.drop_index(op.f('ix_incidents_monitor_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
