"""Crear tabla checks

Revision ID: ece99b38aab1
Revises: 23b66af7d501
Create Date: 2026-08-23 21:01:18.208146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece99b38aab1'
down_revision: Union[str, None] = '23b66af7d501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monitor_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('exitoso', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('tiempo_respuesta_ms', sa.Integer(), nullable=True),
    sa.Column('tipo_error', sa.String(), nullable=True),
    sa.Column('detalle_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checks_monitor_id'), 'checks', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_checks_timestamp'), 'checks', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checks_timestamp'), table_name='checks')
    op.drop_index(op.f('ix_checks_monitor_id'), table_name='checks')
    op.drop_table('checks')
    # ### end Alembic commands ###
